"use client";

import Link from "next/link";
import type { Product } from "@/types/product";

export default function ProductTable({ products, onDelete }: { products: Product[]; onDelete: (product: Product) => void }) {
  return <>
    <div className="hidden overflow-hidden rounded-2xl border bg-white shadow-sm md:block"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Product</th><th className="px-4 py-3">Category</th><th className="px-4 py-3">Price</th><th className="px-4 py-3">Rating</th><th className="px-4 py-3">Stock</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y">{products.map((p) => <tr key={p.id} className="hover:bg-slate-50"><td className="px-4 py-3"><div className="flex items-center gap-3"><img src={p.thumbnail} alt="" className="h-12 w-12 rounded-lg object-cover" /><div><Link href={`/products/${p.id}`} className="font-semibold hover:underline">{p.title}</Link><p className="text-xs text-slate-500">#{p.id}</p></div></div></td><td className="px-4 py-3 capitalize">{p.category}</td><td className="px-4 py-3">${p.price.toFixed(2)}</td><td className="px-4 py-3">⭐ {p.rating.toFixed(1)}</td><td className="px-4 py-3">{p.stock}</td><td className="px-4 py-3 text-right"><Link className="mr-3 font-medium text-blue-600" href={`/products/${p.id}/edit`}>Edit</Link><button onClick={() => onDelete(p)} className="font-medium text-red-600">Delete</button></td></tr>)}</tbody></table></div>
    <div className="space-y-3 md:hidden">{products.map((p) => <article key={p.id} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex gap-3"><img src={p.thumbnail} alt="" className="h-20 w-20 rounded-xl object-cover" /><div className="min-w-0 flex-1"><Link href={`/products/${p.id}`} className="font-semibold hover:underline">{p.title}</Link><p className="mt-1 text-xs capitalize text-slate-500">{p.category}</p><p className="mt-2 font-bold">${p.price.toFixed(2)}</p></div></div><div className="mt-4 flex items-center justify-between text-sm text-slate-600"><span>⭐ {p.rating.toFixed(1)}</span><span>Stock: {p.stock}</span></div><div className="mt-4 flex gap-4 text-sm"><Link className="font-medium text-blue-600" href={`/products/${p.id}/edit`}>Edit</Link><button onClick={() => onDelete(p)} className="font-medium text-red-600">Delete</button></div></article>)}</div>
  </>;
}
